#define PREFIX CVO
#define MAINPREFIX z

#define PREFIX_BEAUTIFIED CVO

#include "script_version.hpp"

// #define VERSION MAJOR.MINOR.PATCHLVL
#define VERSION MAJOR.MINOR
#define VERSION_AR MAJOR,MINOR,PATCHLVL
 